# SPI used by WebCore on iOS.
# More info: https://github.com/WebKit/WebKit/wiki/Using-SPI-on-Apple-platforms

[[temporary-usage]]
request = "rdar://141698311"
cleanup = "rdar://157890302"
classes = ["AXRemoteElement"]
selectors = [
    { name = "setOnClientSide:", class = "?" },
    { name = "initWithUUID:andRemotePid:andContextId:", class = "?" },
]

[[not-web-essential]]
request = "rdar://157890384"
classes = ["MTMaterialLayer"]
symbols = [
    "_MTCoreMaterialRecipeNone",
    "_MTCoreMaterialRecipePlatformChromeDark",
    "_MTCoreMaterialRecipePlatformChromeLight",
    "_MTCoreMaterialRecipePlatformContentDark",
    "_MTCoreMaterialRecipePlatformContentLight",
    "_MTCoreMaterialRecipePlatformContentThickDark",
    "_MTCoreMaterialRecipePlatformContentThickLight",
    "_MTCoreMaterialRecipePlatformContentThinDark",
    "_MTCoreMaterialRecipePlatformContentThinLight",
    "_MTCoreMaterialRecipePlatformContentUltraThinDark",
    "_MTCoreMaterialRecipePlatformContentUltraThinLight",
    "_MTCoreMaterialVisualStyleCategoryFill",
    "_MTCoreMaterialVisualStyleCategoryStroke",
    "_MTCoreMaterialVisualStyleNone",
    "_MTCoreMaterialVisualStylePrimary",
    "_MTCoreMaterialVisualStyleQuaternary",
    "_MTCoreMaterialVisualStyleSecondary",
    "_MTCoreMaterialVisualStyleSeparator",
    "_MTCoreMaterialVisualStyleTertiary",
    "_MTVisualStylingCreateDictionaryRepresentation",
]

[[not-web-essential]]
request = "rdar://157890562"
symbols = [
    # Only used for benchmarking, see 293525@main.
    "_nw_parameters_set_source_application_by_bundle_id",
]

[[temporary-usage]]
request = "rdar://157890014"
cleanup = "rdar://157890142"
symbols = [
    "_nw_path_create_evaluator_for_endpoint",
    "_nw_path_evaluator_copy_path",
    "_nw_resolver_create_with_path",
]
